@startuml

title __INTERACTION's Class Diagram__\n

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.AbstractMouseHandlerFX {
            - altKey : boolean
            - ctrlKey : boolean
            - enabled : boolean
            - id : String
            - metaKey : boolean
            - shiftKey : boolean
            + AbstractMouseHandlerFX()
            + getID()
            + handleMouseClicked()
            + handleMouseDragged()
            + handleMouseMoved()
            + handleMousePressed()
            + handleMouseReleased()
            + handleScroll()
            + hasMatchingModifiers()
            + isEnabled()
            + setEnabled()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.AnchorHandlerFX {
            - mousePressedPoint : Point2D
            + AnchorHandlerFX()
            + handleMouseClicked()
            + handleMousePressed()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.ChartMouseEventFX {
            - chart : JFreeChart
            - entity : ChartEntity
            {static} - serialVersionUID : long
            - trigger : MouseEvent
            + ChartMouseEventFX()
            + getChart()
            + getEntity()
            + getTrigger()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        interface org.jfree.chart.fx.interaction.ChartMouseListenerFX {
            {abstract} + chartMouseClicked()
            {abstract} + chartMouseMoved()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.DispatchHandlerFX {
            - mousePressedPoint : Point2D
            + DispatchHandlerFX()
            + handleMouseClicked()
            + handleMouseMoved()
            + handleMousePressed()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        interface org.jfree.chart.fx.interaction.MouseHandlerFX {
            {abstract} + getID()
            {abstract} + handleMouseClicked()
            {abstract} + handleMouseDragged()
            {abstract} + handleMouseMoved()
            {abstract} + handleMousePressed()
            {abstract} + handleMouseReleased()
            {abstract} + handleScroll()
            {abstract} + hasMatchingModifiers()
            {abstract} + isEnabled()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.PanHandlerFX {
            - panH : double
            - panLast : Point2D
            - panW : double
            + PanHandlerFX()
            + PanHandlerFX()
            + handleMouseDragged()
            + handleMousePressed()
            + handleMouseReleased()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.ScrollHandlerFX {
            - zoomFactor : double
            + ScrollHandlerFX()
            + getZoomFactor()
            + handleScroll()
            + setZoomFactor()
            - handleZoomable()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.TooltipHandlerFX {
            + TooltipHandlerFX()
            + handleMouseMoved()
            - getTooltipText()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace fx {
      namespace interaction {
        class org.jfree.chart.fx.interaction.ZoomHandlerFX {
            - startPoint : Point2D
            - viewer : ChartViewer
            + ZoomHandlerFX()
            + ZoomHandlerFX()
            + handleMouseDragged()
            + handleMousePressed()
            + handleMouseReleased()
            - percentH()
            - percentW()
        }
      }
    }
  }
  

  org.jfree.chart.fx.interaction.AbstractMouseHandlerFX .up.|> MouseHandlerFX
  org.jfree.chart.fx.interaction.ChartMouseEventFX .up.|> Serializable
  org.jfree.chart.fx.interaction.ScrollHandlerFX .up.|> MouseHandlerFX
  org.jfree.chart.fx.interaction.TooltipHandlerFX .up.|> MouseHandlerFX


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
