@startuml

title __DIAL's Class Diagram__\n

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.AbstractDialLayerTest {
            + testCloning()
            + testEquals()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.ArcDialFrameTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.DialBackgroundTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.DialCapTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.DialPlotTest {
            - lastEvent : PlotChangeEvent
            + plotChanged()
            + testBackgroundListener()
            + testCapListener()
            + testCloning()
            + testEquals()
            + testFrameListener()
            + testHashCode()
            + testLayerListener()
            + testScaleListener()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.DialPointerTest {
            + testCloning()
            + testEquals()
            + testEqualsPin()
            + testEqualsPointer()
            + testHashCode()
            + testSerialization()
            + testSerialization2()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.DialTextAnnotationTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.DialValueIndicatorTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.MyDialLayerChangeListener {
            + MyDialLayerChangeListener()
            + dialLayerChanged()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.StandardDialFrameTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.StandardDialRangeTest {
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
        }
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace plot {
      namespace dial {
        class org.jfree.chart.plot.dial.StandardDialScaleTest {
            {static} - EPSILON : double
            + testAngleToValue()
            + testCloning()
            + testEquals()
            + testHashCode()
            + testSerialization()
            + testValueToAngle()
        }
      }
    }
  }
  

  org.jfree.chart.plot.dial.DialPlotTest .up.|> PlotChangeListener
  org.jfree.chart.plot.dial.MyDialLayerChangeListener .up.|> DialLayerChangeListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
