@startuml

title __BLOCK's Class Diagram__\n

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.AbstractBlockTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.BlockBorderTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.BlockContainerTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.BorderArrangementTest {
          {static} - EPSILON : double
          + testBugX()
          + testCloning()
          + testEquals()
          + testSerialization()
          + testSizing()
          + testSizingWithWidthConstraint()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.ColorBlockTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.ColumnArrangementTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.EmptyBlockTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.FlowArrangementTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.GridArrangementTest {
          {static} - EPSILON : double
          + testCloning()
          + testEquals()
          + testFN()
          + testGridNotFull_FF()
          + testGridNotFull_FN()
          + testGridNotFull_FR()
          + testGridNotFull_NN()
          + testNF()
          + testNN()
          + testNR()
          + testNullBlock_FF()
          + testNullBlock_FN()
          + testNullBlock_FR()
          + testNullBlock_NN()
          + testRF()
          + testRN()
          + testRR()
          + testSerialization()
          - createTestContainer1()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.LabelBlockTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.LineBorderTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace block {
      class org.jfree.chart.block.RectangleConstraintTest {
          {static} - EPSILON : double
          + testCalculateConstrainedSize()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
