@startuml

title __TITLE's Class Diagram__\n

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.CompositeTitleTest {
          + testCloning()
          + testConstructor()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.DateTitleTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.ImageTitleTest {
          {static} - EPSILON : double
          + testArrangeNN()
          + testCloning()
          + testEquals()
          + testHashcode()
          + testSerialization()
          + testWidthAndHeight()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.LegendGraphicTest {
          + testCloning()
          + testCloning2()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.LegendTitleTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.PaintScaleLegendTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.ShortTextTitleTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.TextTitleTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace title {
      class org.jfree.chart.title.TitleTest {
          + testEquals()
          + testHashcode()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
