@startuml

title __ENTITY's Class Diagram__\n

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.CategoryItemEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.CategoryLabelEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.ContourEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.LegendItemEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.PieSectionEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.StandardEntityCollectionTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.TickLabelEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace entity {
      class org.jfree.chart.entity.XYItemEntityTest {
          + testCloning()
          + testEquals()
          + testSerialization()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
