@startuml

title __NEEDLE's Class Diagram__\n

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.ArrowNeedle {
          - isArrowAtTop : boolean
          {static} - serialVersionUID : long
          + ArrowNeedle()
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.LineNeedle {
          {static} - serialVersionUID : long
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.LongNeedle {
          {static} - serialVersionUID : long
          + LongNeedle()
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      abstract class org.jfree.chart.needle.MeterNeedle {
          {static} # transform : AffineTransform
          - fillPaint : Paint
          - highlightPaint : Paint
          - outlinePaint : Paint
          - outlineStroke : Stroke
          - rotateX : double
          - rotateY : double
          {static} - serialVersionUID : long
          - size : int
          + MeterNeedle()
          + MeterNeedle()
          + draw()
          + draw()
          + draw()
          + equals()
          + getFillPaint()
          + getHighlightPaint()
          + getOutlinePaint()
          + getOutlineStroke()
          + getRotateX()
          + getRotateY()
          + getSize()
          + getTransform()
          + hashCode()
          + setFillPaint()
          + setHighlightPaint()
          + setOutlinePaint()
          + setOutlineStroke()
          + setRotateX()
          + setRotateY()
          + setSize()
          # defaultDisplay()
          {abstract} # drawNeedle()
          - readObject()
          - writeObject()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.MiddlePinNeedle {
          {static} - serialVersionUID : long
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.PinNeedle {
          {static} - serialVersionUID : long
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.PlumNeedle {
          {static} - serialVersionUID : long
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.PointerNeedle {
          {static} - serialVersionUID : long
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.ShipNeedle {
          {static} - serialVersionUID : long
          + clone()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace needle {
      class org.jfree.chart.needle.WindNeedle {
          {static} - serialVersionUID : long
          + WindNeedle()
          + equals()
          + hashCode()
          # drawNeedle()
      }
    }
  }
  

  org.jfree.chart.needle.ArrowNeedle .up.|> Cloneable
  org.jfree.chart.needle.ArrowNeedle .up.|> Serializable
  org.jfree.chart.needle.LineNeedle .up.|> Cloneable
  org.jfree.chart.needle.LineNeedle .up.|> Serializable
  org.jfree.chart.needle.LongNeedle .up.|> Cloneable
  org.jfree.chart.needle.LongNeedle .up.|> Serializable
  org.jfree.chart.needle.MeterNeedle .up.|> Serializable
  org.jfree.chart.needle.MiddlePinNeedle .up.|> Cloneable
  org.jfree.chart.needle.MiddlePinNeedle .up.|> Serializable
  org.jfree.chart.needle.PinNeedle .up.|> Cloneable
  org.jfree.chart.needle.PinNeedle .up.|> Serializable
  org.jfree.chart.needle.PlumNeedle .up.|> Cloneable
  org.jfree.chart.needle.PlumNeedle .up.|> Serializable
  org.jfree.chart.needle.PointerNeedle .up.|> Cloneable
  org.jfree.chart.needle.PointerNeedle .up.|> Serializable
  org.jfree.chart.needle.ShipNeedle .up.|> Cloneable
  org.jfree.chart.needle.ShipNeedle .up.|> Serializable
  org.jfree.chart.needle.WindNeedle .up.|> Cloneable
  org.jfree.chart.needle.WindNeedle .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
