@startuml

title __ENCODERS's Class Diagram__\n

  namespace org.jfree.chart {
    namespace encoders {
      class org.jfree.chart.encoders.EncoderUtil {
          {static} + encode()
          {static} + encode()
          {static} + encode()
          {static} + encode()
          {static} + writeBufferedImage()
          {static} + writeBufferedImage()
          {static} + writeBufferedImage()
          {static} + writeBufferedImage()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace encoders {
      interface org.jfree.chart.encoders.ImageEncoder {
          {abstract} + encode()
          {abstract} + encode()
          {abstract} + getQuality()
          {abstract} + isEncodingAlpha()
          {abstract} + setEncodingAlpha()
          {abstract} + setQuality()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace encoders {
      class org.jfree.chart.encoders.ImageEncoderFactory {
          {static} - encoders : Map
          {static} + newInstance()
          {static} + newInstance()
          {static} + newInstance()
          {static} + newInstance()
          {static} + setImageEncoder()
          {static} - init()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace encoders {
      interface org.jfree.chart.encoders.ImageFormat {
          {static} + GIF : String
          {static} + JPEG : String
          {static} + PNG : String
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace encoders {
      class org.jfree.chart.encoders.KeypointPNGEncoderAdapter {
          - encodingAlpha : boolean
          - quality : int
          + encode()
          + encode()
          + getQuality()
          + isEncodingAlpha()
          + setEncodingAlpha()
          + setQuality()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace encoders {
      class org.jfree.chart.encoders.SunJPEGEncoderAdapter {
          - quality : float
          + SunJPEGEncoderAdapter()
          + encode()
          + encode()
          + getQuality()
          + isEncodingAlpha()
          + setEncodingAlpha()
          + setQuality()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace encoders {
      class org.jfree.chart.encoders.SunPNGEncoderAdapter {
          + encode()
          + encode()
          + getQuality()
          + isEncodingAlpha()
          + setEncodingAlpha()
          + setQuality()
      }
    }
  }
  

  org.jfree.chart.encoders.KeypointPNGEncoderAdapter .up.|> ImageEncoder
  org.jfree.chart.encoders.SunJPEGEncoderAdapter .up.|> ImageEncoder
  org.jfree.chart.encoders.SunPNGEncoderAdapter .up.|> ImageEncoder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
