@startuml

title __ANNOTATIONS's Class Diagram__\n

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.CategoryLineAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.CategoryPointerAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.CategoryTextAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashcode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.TextAnnotationTest {
          - lastEvent : AnnotationChangeEvent
          + annotationChanged()
          + testChangeEvents()
          + testEquals()
          + testHashCode()
          + testSetRotationAnchor()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYBoxAnnotationTest {
          + testCloning()
          + testDrawWithNullInfo()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYDrawableAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYDrawableAnnotationTest.TestDrawable {
          + TestDrawable()
          + clone()
          + draw()
          + equals()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYImageAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYLineAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYPointerAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYPolygonAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYShapeAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYTextAnnotationTest {
          + testCloning()
          + testEquals()
          + testHashCode()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace annotations {
      class org.jfree.chart.annotations.XYTitleAnnotationTest {
          + testCloning()
          + testDrawWithNullInfo()
          + testEquals()
          + testHashCode()
          + testSerialization()
      }
    }
  }
  

  org.jfree.chart.annotations.TextAnnotationTest .up.|> AnnotationChangeListener
  org.jfree.chart.annotations.XYDrawableAnnotationTest +-down- org.jfree.chart.annotations.XYDrawableAnnotationTest.TestDrawable
  org.jfree.chart.annotations.XYDrawableAnnotationTest.TestDrawable .up.|> Cloneable
  org.jfree.chart.annotations.XYDrawableAnnotationTest.TestDrawable .up.|> Drawable
  org.jfree.chart.annotations.XYDrawableAnnotationTest.TestDrawable .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
