@startuml

title __EVENT's Class Diagram__\n

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.AnnotationChangeEvent {
          - annotation : Annotation
          + AnnotationChangeEvent()
          + getAnnotation()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.AnnotationChangeListener {
          {abstract} + annotationChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.AxisChangeEvent {
          - axis : Axis
          + AxisChangeEvent()
          + getAxis()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.AxisChangeListener {
          {abstract} + axisChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.ChartChangeEvent {
          - chart : JFreeChart
          - type : ChartChangeEventType
          + ChartChangeEvent()
          + ChartChangeEvent()
          + ChartChangeEvent()
          + getChart()
          + getType()
          + setChart()
          + setType()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.ChartChangeEventType {
          {static} + DATASET_UPDATED : ChartChangeEventType
          {static} + GENERAL : ChartChangeEventType
          {static} + NEW_DATASET : ChartChangeEventType
          - name : String
          {static} - serialVersionUID : long
          + equals()
          + hashCode()
          + toString()
          - ChartChangeEventType()
          - readResolve()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.ChartChangeListener {
          {abstract} + chartChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.ChartProgressEvent {
          {static} + DRAWING_FINISHED : int
          {static} + DRAWING_STARTED : int
          - chart : JFreeChart
          - percent : int
          - type : int
          + ChartProgressEvent()
          + getChart()
          + getPercent()
          + getType()
          + setChart()
          + setPercent()
          + setType()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.ChartProgressListener {
          {abstract} + chartProgress()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.MarkerChangeEvent {
          - marker : Marker
          + MarkerChangeEvent()
          + getMarker()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.MarkerChangeListener {
          {abstract} + markerChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.OverlayChangeEvent {
          + OverlayChangeEvent()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.OverlayChangeListener {
          {abstract} + overlayChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.PlotChangeEvent {
          - plot : Plot
          + PlotChangeEvent()
          + getPlot()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.PlotChangeListener {
          {abstract} + plotChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.RendererChangeEvent {
          - renderer : Object
          - seriesVisibilityChanged : boolean
          + RendererChangeEvent()
          + RendererChangeEvent()
          + getRenderer()
          + getSeriesVisibilityChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.RendererChangeListener {
          {abstract} + rendererChanged()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      class org.jfree.chart.event.TitleChangeEvent {
          - title : Title
          + TitleChangeEvent()
          + getTitle()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace event {
      interface org.jfree.chart.event.TitleChangeListener {
          {abstract} + titleChanged()
      }
    }
  }
  

  org.jfree.chart.event.ChartChangeEventType .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
