@startuml

title __EDITOR's Class Diagram__\n

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTAxisEditor {
          {static} # localizationResources : ResourceBundle
          - font : Font
          - label : Text
          - labelFont : FontData
          - labelFontField : Text
          - labelPaintColor : Color
          - otherTabs : TabFolder
          - showTickLabelsCheckBox : Button
          - showTickMarksCheckBox : Button
          - tickLabelFont : FontData
          - tickLabelFontField : Text
          - tickLabelPaintColor : Color
          + SWTAxisEditor()
          {static} + getInstance()
          + getLabel()
          + getLabelFont()
          + getLabelPaint()
          + getOtherTabs()
          + getTickLabelFont()
          + getTickLabelPaint()
          + setAxisProperties()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTChartEditor {
          {static} # localizationResources : ResourceBundle
          - chart : JFreeChart
          - otherEditor : SWTOtherEditor
          - plotEditor : SWTPlotEditor
          - shell : Shell
          - titleEditor : SWTTitleEditor
          + SWTChartEditor()
          + open()
          + updateChart()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTNumberAxisEditor {
          - autoRange : boolean
          - autoRangeCheckBox : Button
          - maximumRangeValue : Text
          - maximumValue : double
          - minimumRangeValue : Text
          - minimumValue : double
          + SWTNumberAxisEditor()
          + focusGained()
          + focusLost()
          + setAxisProperties()
          + toggleAutoRange()
          + validateMaximum()
          + validateMinimum()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTOtherEditor {
          {static} # localizationResources : ResourceBundle
          - antialias : Button
          - backgroundPaintCanvas : SWTPaintCanvas
          + SWTOtherEditor()
          + updateChartProperties()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTPlotAppearanceEditor {
          {static} # localizationResources : ResourceBundle
          {static} - ORIENTATION_HORIZONTAL : int
          {static} - ORIENTATION_VERTICAL : int
          - backgroundPaintCanvas : SWTPaintCanvas
          - orientation : Combo
          {static} - orientationNames : String[]
          - outlinePaintCanvas : SWTPaintCanvas
          - plotOrientation : PlotOrientation
          - selectStroke : Spinner
          - strokeCanvas : SWTStrokeCanvas
          + getBackGroundPaint()
          + getOutlinePaint()
          + getPlotOrientation()
          + getStroke()
          ~ SWTPlotAppearanceEditor()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTPlotEditor {
          {static} # localizationResources : ResourceBundle
          - domainAxisPropertyPanel : SWTAxisEditor
          - plotAppearance : SWTPlotAppearanceEditor
          - rangeAxisPropertyPanel : SWTAxisEditor
          + SWTPlotEditor()
          + getBackgroundPaint()
          + getOutlinePaint()
          + getOutlineStroke()
          + updatePlotProperties()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTStrokeCanvas {
          + SWTStrokeCanvas()
          + SWTStrokeCanvas()
          + getStroke()
          + setStroke()
      }
    }
  }
  

  namespace org.jfree.experimental.chart.swt {
    namespace editor {
      class org.jfree.experimental.chart.swt.editor.SWTTitleEditor {
          {static} # localizationResources : ResourceBundle
          - font : Font
          - fontField : Text
          - selectColorButton : Button
          - selectFontButton : Button
          - showTitle : boolean
          - showTitleCheckBox : Button
          - titleColor : Color
          - titleField : Text
          - titleFont : FontData
          + getTitleColor()
          + getTitleFont()
          + getTitleText()
          + setTitleProperties()
          ~ SWTTitleEditor()
      }
    }
  }
  

  org.jfree.experimental.chart.swt.editor.SWTChartEditor .up.|> ChartEditor
  org.jfree.experimental.chart.swt.editor.SWTNumberAxisEditor .up.|> FocusListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
