@startuml

title __URLS's Class Diagram__\n

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.CustomCategoryURLGeneratorTest {
          + testAddURLSeries()
          + testCloning()
          + testEquals()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.CustomPieURLGeneratorTest {
          + testCloning()
          + testEquals()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.CustomXYURLGeneratorTest {
          + testAddURLSeries()
          + testCloning()
          + testEquals()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.StandardCategoryURLGeneratorTest {
          + testEquals()
          + testGenerateURL()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.StandardPieURLGeneratorTest {
          + testEquals()
          + testPublicCloneable()
          + testSerialization()
          + testURL()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.StandardXYURLGeneratorTest {
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace urls {
      class org.jfree.chart.urls.TimeSeriesURLGeneratorTest {
          + testEquals()
          + testGenerateURL()
          + testPublicCloneable()
          + testSerialization()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
