@startuml

title __SERVLET's Class Diagram__\n

  namespace org.jfree.chart {
    namespace servlet {
      class org.jfree.chart.servlet.ChartDeleter {
          - chartNames : List
          + ChartDeleter()
          + addChart()
          + isChartAvailable()
          + valueBound()
          + valueUnbound()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace servlet {
      class org.jfree.chart.servlet.DisplayChart {
          + DisplayChart()
          + init()
          + service()
      }
    }
  }
  

  namespace org.jfree.chart {
    namespace servlet {
      class org.jfree.chart.servlet.ServletUtilities {
          {static} - tempFilePrefix : String
          {static} - tempOneTimeFilePrefix : String
          {static} + getTempFilePrefix()
          {static} + getTempOneTimeFilePrefix()
          {static} + saveChartAsJPEG()
          {static} + saveChartAsJPEG()
          {static} + saveChartAsPNG()
          {static} + saveChartAsPNG()
          {static} + searchReplace()
          {static} + sendTempFile()
          {static} + sendTempFile()
          {static} + sendTempFile()
          {static} + setTempFilePrefix()
          {static} + setTempOneTimeFilePrefix()
          {static} # createTempDir()
          {static} # registerChartForDeletion()
      }
    }
  }
  

  org.jfree.chart.servlet.ChartDeleter .up.|> HttpSessionBindingListener
  org.jfree.chart.servlet.ChartDeleter .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
